import sys
from pathlib import Path
from datetime import datetime, timezone

# Ensure ai_engine root is in sys.path
sys.path.append(str(Path(__file__).resolve().parent.parent))

from sqlalchemy import Column, Integer, String, Float, Date, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from database.connection import Base

# ==========================================
# EXISTING APPLICATION TABLES (READ ONLY)
# ==========================================

class StudentModel(Base):
    """
    Mapped ORM Model for existing 'students' database table.
    """
    __tablename__ = "students"

    student_id = Column(Integer, primary_key=True, index=True)
    department = Column(String(100), nullable=False, index=True)
    semester = Column(Integer, nullable=False, index=True)
    section = Column(String(10), nullable=False)

    # Relationships
    attendances = relationship("AttendanceModel", back_populates="student")
    leaves = relationship("LeaveModel", back_populates="student")


class FacultyModel(Base):
    """
    Mapped ORM Model for existing 'faculty' database table.
    """
    __tablename__ = "faculty"

    faculty_id = Column(Integer, primary_key=True, index=True)
    department = Column(String(100), nullable=False, index=True)

    # Relationships
    subjects = relationship("SubjectModel", back_populates="faculty")


class SubjectModel(Base):
    """
    Mapped ORM Model for existing 'subjects' database table.
    """
    __tablename__ = "subjects"

    subject_id = Column(Integer, primary_key=True, index=True)
    faculty_id = Column(Integer, ForeignKey("faculty.faculty_id"), nullable=False)
    subject_name = Column(String(150), nullable=False)

    # Relationships
    faculty = relationship("FacultyModel", back_populates="subjects")
    attendances = relationship("AttendanceModel", back_populates="subject")


class AttendanceModel(Base):
    """
    Mapped ORM Model for existing 'attendance' database table.
    """
    __tablename__ = "attendance"

    attendance_id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.student_id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.subject_id"), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    status = Column(String(20), nullable=False)  # PRESENT, ABSENT, LATE, EXCUSED

    # Relationships
    student = relationship("StudentModel", back_populates="attendances")
    subject = relationship("SubjectModel", back_populates="attendances")


class LeaveModel(Base):
    """
    Mapped ORM Model for existing 'leaves' database table.
    """
    __tablename__ = "leaves"

    leave_id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.student_id"), nullable=False, index=True)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)
    reason = Column(Text, nullable=True)

    # Relationships
    student = relationship("StudentModel", back_populates="leaves")


class AcademicCalendarModel(Base):
    """
    Mapped ORM Model for college academic calendar (holidays, exams, festivals).
    """
    __tablename__ = "academic_calendar"

    id = Column(Integer, primary_key=True, index=True)
    date = Column(Date, nullable=False, unique=True, index=True)
    holiday_name = Column(String(100), nullable=True)
    holiday_type = Column(String(50), nullable=True)  # NATIONAL, FESTIVAL, ACADEMIC_BREAK, EXAM, VACATION, SPECIAL_WORKING_DAY, OTHER
    is_holiday = Column(Integer, default=1, nullable=False)  # 1 = True, 0 = False
    source_pdf = Column(String(255), nullable=True)
    source_page = Column(Integer, nullable=True)
    source_type = Column(String(50), default="SYNTHETIC_DEVELOPMENT", nullable=True)  # SYNTHETIC_DEVELOPMENT or UPLOADED_PDF
    academic_year = Column(String(50), nullable=True)
    semester = Column(String(50), nullable=True)


# ==========================================
# AI MODULE DEDICATED OUTPUT TABLES
# ==========================================

class PredictionResultModel(Base):
    """
    Stores student attendance predictions generated by ML models.
    """
    __tablename__ = "prediction_results"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.student_id"), nullable=False, index=True)
    predicted_pct = Column(Float, nullable=False)
    risk_level = Column(String(20), nullable=False, index=True)  # LOW, MEDIUM, HIGH, CRITICAL
    explanation = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)


class AIAlertModel(Base):
    """
    Stores contextual dashboard alerts generated for students or faculty.
    """
    __tablename__ = "ai_alerts"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.student_id"), nullable=True, index=True)
    alert_type = Column(String(50), nullable=False)
    message = Column(Text, nullable=False)
    severity = Column(String(20), nullable=False)  # INFO, WARNING, CRITICAL
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), index=True)


class PatternAnalysisModel(Base):
    """
    Stores pattern analysis findings (weekday trends, holiday effects, subject trends).
    """
    __tablename__ = "pattern_analysis"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, nullable=True, index=True)
    department = Column(String(100), nullable=True, index=True)
    pattern_type = Column(String(50), nullable=False)
    pattern_summary = Column(Text, nullable=False)
    data_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class RecommendationModel(Base):
    """
    Stores personalized student actionable recommendations.
    """
    __tablename__ = "recommendations"

    id = Column(Integer, primary_key=True, index=True)
    student_id = Column(Integer, ForeignKey("students.student_id"), nullable=False, index=True)
    recommendation_text = Column(Text, nullable=False)
    priority = Column(String(20), default="MEDIUM")
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class FacultyAnalyticsModel(Base):
    """
    Stores faculty and subject-level classroom analytics.
    """
    __tablename__ = "faculty_analytics"

    id = Column(Integer, primary_key=True, index=True)
    faculty_id = Column(Integer, ForeignKey("faculty.faculty_id"), nullable=False, index=True)
    subject_id = Column(Integer, ForeignKey("subjects.subject_id"), nullable=True)
    class_avg_pct = Column(Float, nullable=False)
    at_risk_count = Column(Integer, nullable=False)
    insights_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))


class GeneratedReportModel(Base):
    """
    Stores generated PDF/Excel reports metadata.
    """
    __tablename__ = "generated_reports"

    id = Column(Integer, primary_key=True, index=True)
    report_type = Column(String(50), nullable=False)  # STUDENT, FACULTY, ADMIN
    target_id = Column(Integer, nullable=True)
    file_path = Column(String(255), nullable=False)
    summary_text = Column(Text, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
